import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getTrans, translatePlanet, translateSign } from './i18n';

const _SIGNS = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];

function addHeader(doc: jsPDF, title: string, pageNum: number, total: number) {
    doc.setFillColor(15, 15, 35);
    doc.rect(0, 0, 210, 22, 'F');
    doc.setFontSize(7); doc.setTextColor(249, 115, 22); doc.setFont('helvetica', 'bold');
    doc.text('JyotishConnect', 15, 14);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180);
    doc.text(title, 105, 14, { align: 'center' });
    doc.text(`Page ${pageNum} / ${total}`, 195, 14, { align: 'right' });
}

function sectionTitle(doc: jsPDF, text: string, y: number, r = 249, g = 115, b = 22) {
    doc.setFontSize(13); doc.setTextColor(r, g, b); doc.setFont('helvetica', 'bold');
    doc.text(text, 15, y);
    doc.setDrawColor(r, g, b); doc.setLineWidth(0.4);
    doc.line(15, y + 2, 195, y + 2);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(30, 30, 30);
}

export async function generateKundliPDF(
    chart: any,
    formData: { name: string; dob: string; tob: string; birthplace: string },
    locale: string,
    chartImages: { d1?: string | null; d9?: string | null; moon?: string | null; d10?: string | null }
) {
    const trans = getTrans(locale);
    const doc = new jsPDF('p', 'mm', 'a4');
    const TOTAL_PAGES = 18;

    // ─── PAGE 1: Cover ──────────────────────────────────────────
    doc.setFillColor(10, 10, 30); doc.rect(0, 0, 210, 297, 'F');
    doc.setFillColor(249, 115, 22); doc.rect(0, 118, 210, 58, 'F');
    doc.setFontSize(30); doc.setTextColor(249, 115, 22); doc.setFont('helvetica', 'bold');
    doc.text('JyotishConnect', 105, 75, { align: 'center' });
    doc.setFontSize(12); doc.setTextColor(200, 200, 200); doc.setFont('helvetica', 'normal');
    doc.text('Premium Vedic Astrology Report', 105, 90, { align: 'center' });
    doc.setFontSize(22); doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold');
    doc.text(formData.name || 'Your Name', 105, 140, { align: 'center' });
    doc.setFontSize(10); doc.setTextColor(255, 220, 180); doc.setFont('helvetica', 'normal');
    doc.text(`${formData.dob}  |  ${formData.tob}  |  ${formData.birthplace}`, 105, 153, { align: 'center' });
    doc.setFontSize(10); doc.setTextColor(150, 150, 150);
    doc.text(`Lagna: ${translateSign(chart.ascendantSign, locale)}  |  Rasi: ${translateSign(chart.moonSign, locale)}  |  Nakshatra: ${chart.nakshatra}`, 105, 200, { align: 'center' });
    doc.setFontSize(7); doc.text('Generated by JyotishConnect — jyotishconnect.com', 105, 280, { align: 'center' });

    // ─── PAGE 2: Birth Details & Avakahada ──────────────────────
    doc.addPage(); addHeader(doc, 'Birth Attributes & Avakahada', 2, TOTAL_PAGES);
    sectionTitle(doc, 'Birth Details', 32);
    autoTable(doc, {
        startY: 37, margin: { left: 15 },
        head: [['Field', 'Value']],
        body: [
            ['Name', formData.name], ['Date of Birth', formData.dob],
            ['Time of Birth', formData.tob], ['Place of Birth', formData.birthplace],
            ['Lagna (Ascendant)', translateSign(chart.ascendantSign, locale)],
            ['Moon Sign (Rasi)', translateSign(chart.moonSign, locale)],
            ['Nakshatra', chart.nakshatra || '—'],
        ],
        styles: { fontSize: 10, cellPadding: 4 },
        headStyles: { fillColor: [249, 115, 22], textColor: 255 },
        alternateRowStyles: { fillColor: [250, 250, 250] },
    });
    const y2 = (doc as any).lastAutoTable.finalY + 10;
    sectionTitle(doc, 'Avakahada Chakra', y2, 79, 70, 229);
    autoTable(doc, {
        startY: y2 + 5, margin: { left: 15 },
        head: [['Attribute', 'Value', 'Attribute', 'Value']],
        body: [
            ['Varna', chart.avakahada?.varna || '—', 'Vashya', chart.avakahada?.vashya || '—'],
            ['Tara', chart.avakahada?.tara || '—', 'Yoni', chart.avakahada?.yoni || '—'],
            ['Gana', chart.avakahada?.gana || '—', 'Nadi', chart.avakahada?.nadi || '—'],
            ['Rashish (Moon Lord)', chart.avakahada?.rashish || '—', 'Bhakoot', chart.avakahada?.bhakoot || '—'],
        ],
        styles: { fontSize: 10, cellPadding: 4 },
        headStyles: { fillColor: [79, 70, 229], textColor: 255 },
        alternateRowStyles: { fillColor: [248, 248, 255] },
    });

    // ─── PAGE 3: Panchang ────────────────────────────────────────
    doc.addPage(); addHeader(doc, 'Daily Panchang at Birth', 3, TOTAL_PAGES);
    sectionTitle(doc, 'Panchang Details', 32);
    autoTable(doc, {
        startY: 37, margin: { left: 15 },
        head: [['Panchang Element', 'Value']],
        body: [
            ['Tithi', chart.panchang?.tithi || '—'],
            ['Nakshatra', chart.nakshatra || '—'],
            ['Yoga', chart.panchang?.yoga || '—'],
            ['Karana', chart.panchang?.karana || '—'],
            ['Vara (Day of Week)', chart.panchang?.vara || '—'],
            ['Sunrise', chart.panchang?.sunrise || '—'],
            ['Sunset', chart.panchang?.sunset || '—'],
        ],
        styles: { fontSize: 11, cellPadding: 5 },
        headStyles: { fillColor: [30, 90, 180], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 248, 255] },
    });

    // ─── PAGES 4-7: Charts ───────────────────────────────────────
    const chartDefs = [
        { img: chartImages.d1, label: 'Lagna / Birth Chart (D1)', page: 4 },
        { img: chartImages.d9, label: 'Navamsa Chart (D9)', page: 5 },
        { img: chartImages.moon, label: 'Chandra Lagna (Moon Chart)', page: 6 },
        { img: chartImages.d10, label: 'Dasamsa Chart (D10)', page: 7 },
    ];
    chartDefs.forEach(({ img, label, page }) => {
        doc.addPage(); addHeader(doc, label, page, TOTAL_PAGES);
        sectionTitle(doc, label, 32);
        if (img) {
            doc.addImage(img, 'PNG', 35, 42, 140, 140);
        } else {
            doc.setFontSize(10); doc.setTextColor(150, 150, 150);
            doc.text('Chart image not available — please view on website.', 105, 120, { align: 'center' });
        }
    });

    // ─── PAGE 8: Planetary Positions ────────────────────────────
    doc.addPage(); addHeader(doc, 'Planetary Positions', 8, TOTAL_PAGES);
    sectionTitle(doc, 'Planetary Positions', 32);
    autoTable(doc, {
        startY: 38, margin: { left: 15 },
        head: [['Planet', 'Sign', 'Degree', 'Nakshatra', 'House', 'Status']],
        body: (chart.planets || []).map((p: any) => [
            translatePlanet(p.name, locale),
            translateSign(p.sign, locale),
            `${Math.floor(p.longitude % 30)}\u00b0 ${Math.floor((p.longitude % 1) * 60)}'`,
            trans.nakshatras?.[p.nakshatraId - 1] || '—',
            p.house || '—',
            p.isExalted ? 'Exalted' : p.isDebilitated ? 'Debilitated' : 'Neutral',
        ]),
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [109, 40, 217], textColor: 255 },
        alternateRowStyles: { fillColor: [248, 245, 255] },
    });

    // ─── PAGE 9: Dasha Timeline ──────────────────────────────────
    doc.addPage(); addHeader(doc, 'Vimshottari Dasha', 9, TOTAL_PAGES);
    sectionTitle(doc, 'Current Dasha', 32);
    const curLords = chart.dasha?.currentLords || [];
    autoTable(doc, {
        startY: 38, margin: { left: 15 }, tableWidth: 100,
        head: [['Level', 'Planet Lord']],
        body: [
            ['Mahadasha', translatePlanet(curLords[0] || '—', locale)],
            ['Antardasha', translatePlanet(curLords[1] || '—', locale)],
            ['Pratyantardasha', translatePlanet(curLords[2] || '—', locale)],
        ],
        styles: { fontSize: 11, cellPadding: 5 },
        headStyles: { fillColor: [249, 115, 22], textColor: 255 },
    });
    const y9 = (doc as any).lastAutoTable.finalY + 10;
    sectionTitle(doc, 'Full Mahadasha Timeline', y9, 79, 70, 229);
    autoTable(doc, {
        startY: y9 + 5, margin: { left: 15 },
        head: [['Planet', 'Start', 'End', 'Duration', 'Status']],
        body: (chart.dasha?.periods || []).map((p: any) => {
            const now = Date.now();
            const s = new Date(p.start), e = new Date(p.end);
            const isActive = now >= s.getTime() && now <= e.getTime();
            return [
                translatePlanet(p.lord, locale),
                s.toLocaleDateString('en-IN', { year: 'numeric', month: 'short' }),
                e.toLocaleDateString('en-IN', { year: 'numeric', month: 'short' }),
                `${Math.round(p.duration)} yrs`,
                isActive ? '▶ ACTIVE' : now > e.getTime() ? 'Completed' : 'Upcoming',
            ];
        }),
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [79, 70, 229], textColor: 255 },
        alternateRowStyles: { fillColor: [248, 248, 255] },
        didParseCell: (data: any) => {
            if (data.column.index === 4 && String(data.cell.raw).includes('ACTIVE')) {
                data.cell.styles.textColor = [249, 115, 22];
                data.cell.styles.fontStyle = 'bold';
            }
        },
    });

    // ─── PAGE 10: Ashtakvarga ────────────────────────────────────
    doc.addPage(); addHeader(doc, 'Ashtakvarga Analysis', 10, TOTAL_PAGES);
    sectionTitle(doc, 'Sarvashtakvarga Points', 32);
    doc.setFontSize(8.5); doc.setTextColor(100, 100, 100);
    doc.text('30+ = Excellent  |  25-29 = Good  |  20-24 = Medium  |  Below 20 = Weak', 15, 40);
    autoTable(doc, {
        startY: 45, margin: { left: 15 },
        head: [['Sign', 'Points', 'Strength', 'Sign', 'Points', 'Strength']],
        body: (() => {
            const rows: any[] = [];
            for (let i = 0; i < 12; i += 2) {
                const p1 = chart.ashtakvarga?.sarva?.[i] ?? 28;
                const p2 = chart.ashtakvarga?.sarva?.[i + 1] ?? 28;
                const str = (n: number) => n >= 30 ? 'Excellent' : n >= 25 ? 'Good' : n >= 20 ? 'Medium' : 'Weak';
                rows.push([
                    translateSign(_SIGNS[i], locale), p1, str(p1),
                    translateSign(_SIGNS[i + 1], locale), p2, str(p2),
                ]);
            }
            return rows;
        })(),
        styles: { fontSize: 10, cellPadding: 4 },
        headStyles: { fillColor: [161, 98, 7], textColor: 255 },
        alternateRowStyles: { fillColor: [255, 251, 235] },
    });

    // ─── PAGE 11: Dosha Analysis ─────────────────────────────────
    doc.addPage(); addHeader(doc, 'Dosha Analysis', 11, TOTAL_PAGES);
    sectionTitle(doc, 'Dosha Analysis', 32);
    let yD = 40;
    Object.entries(chart.doshas || {}).forEach(([key, data]: [string, any]) => {
        const info = trans.doshas?.[key];
        const name = info?.name || key;
        const desc = info?.description || data.description || 'No major influence detected.';
        const remedies: string[] = data.present ? (info?.remedies || []) : [];
        const boxH = 28 + remedies.length * 5.5;
        if (yD + boxH > 270) { doc.addPage(); addHeader(doc, 'Dosha Analysis (contd.)', 11, TOTAL_PAGES); yD = 30; }
        const [fr, fg, fb] = data.present ? [255, 240, 240] : [240, 255, 245];
        const [dr, dg, db] = data.present ? [220, 50, 50] : [34, 197, 94];
        doc.setFillColor(fr, fg, fb); doc.setDrawColor(dr, dg, db); doc.setLineWidth(0.5);
        doc.roundedRect(15, yD, 180, boxH, 2, 2, 'FD');
        doc.setFontSize(11); doc.setTextColor(30, 30, 30); doc.setFont('helvetica', 'bold');
        doc.text(`${name}  —  ${data.present ? 'PRESENT' : 'ABSENT'}`, 20, yD + 8);
        doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(70, 70, 70);
        const dLines = doc.splitTextToSize(desc, 168);
        doc.text(dLines, 20, yD + 15);
        if (remedies.length) {
            doc.setFontSize(8); doc.setTextColor(249, 115, 22);
            doc.text('Remedies:', 20, yD + 15 + dLines.length * 5);
            doc.setTextColor(60, 60, 60);
            remedies.forEach((r: string, ri: number) => {
                doc.text(`• ${r}`, 24, yD + 20 + dLines.length * 5 + ri * 5.5);
            });
        }
        yD += boxH + 6;
    });

    // ─── PAGES 12-16: Life Predictions ──────────────────────────
    const predEntries = Object.entries(chart.predictions || {});
    predEntries.forEach(([area, text]: [string, any], pi) => {
        doc.addPage();
        const pageNum = 12 + pi;
        const label = (trans.labels?.life_predictions as any)?.[area] || area;
        addHeader(doc, `${label}`, pageNum, TOTAL_PAGES);
        sectionTitle(doc, label, 32, 79, 70, 229);
        doc.setFontSize(11); doc.setTextColor(40, 40, 40);
        const lines = doc.splitTextToSize(String(text || 'Prediction data not available.'), 175);
        doc.text(lines, 15, 44);
    });

    // ─── PAGE 17: Remedies ───────────────────────────────────────
    doc.addPage(); addHeader(doc, 'Remedies & Gemstones', 17, TOTAL_PAGES);
    sectionTitle(doc, 'Gemstone Recommendations', 32);
    const gs = trans.gemstones || {};
    autoTable(doc, {
        startY: 38, margin: { left: 15 },
        head: [['Type', 'Gemstone', 'Wear Day', 'Finger', 'Metal', 'Weight', 'Mantra']],
        body: [
            ['Life Stone', gs['Sun'] || 'Ruby', 'Sunday', 'Ring Finger', 'Gold', '3-5 Ratti', 'Om Suryaya Namah'],
            ['Lucky Stone', gs['Jupiter'] || 'Yellow Sapphire', 'Thursday', 'Index Finger', 'Gold', '5-7 Ratti', 'Om Guruve Namah'],
            ['Benefic Stone', gs['Moon'] || 'Pearl', 'Monday', 'Little Finger', 'Silver', '5-7 Ratti', 'Om Chandraya Namah'],
        ],
        styles: { fontSize: 8.5, cellPadding: 3 },
        headStyles: { fillColor: [161, 98, 7], textColor: 255 },
        alternateRowStyles: { fillColor: [255, 251, 235] },
    });
    const yRem = (doc as any).lastAutoTable.finalY + 10;
    sectionTitle(doc, 'Spiritual Remedies', yRem, 79, 70, 229);
    autoTable(doc, {
        startY: yRem + 5, margin: { left: 15 },
        head: [['Remedy', 'Details']],
        body: [
            ['Mahadasha Remedy', `${translatePlanet(chart.dasha?.currentLords?.[0] || 'Sun', locale)} ki Mahadasha chal rahi hai. Inke Beej Mantra ka 108 baar jaap karo pratidin.`],
            ['Shani Remedy', 'Shanivar ko peeple ke ped ko jal chadhaein. Kale til, urad dal ya sarson ka tel daan karo.'],
            ['Mangal Remedy', 'Mangalwar ko Hanuman Chalisa padhein. Lal kapde mein moonga donate karein.'],
            ['Surya Remedy', 'Pratidin subah surya ko lal pushp milakar jal chadhaein. Aditya Hridayam ka paath karein.'],
        ],
        styles: { fontSize: 9.5, cellPadding: 4 },
        headStyles: { fillColor: [79, 70, 229], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 245, 255] },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
    });

    // ─── PAGE 18: Conclusion ─────────────────────────────────────
    doc.addPage(); addHeader(doc, 'Summary & Blessings', 18, TOTAL_PAGES);
    doc.setFillColor(10, 10, 30); doc.rect(0, 22, 210, 275, 'F');
    doc.setFontSize(20); doc.setTextColor(249, 115, 22); doc.setFont('helvetica', 'bold');
    doc.text('Blessings & Divine Guidance', 105, 80, { align: 'center' });
    doc.setFontSize(12); doc.setTextColor(200, 200, 200); doc.setFont('helvetica', 'normal');
    doc.text(`Dear ${formData.name},`, 105, 105, { align: 'center' });
    const bless = doc.splitTextToSize('May the celestial alignments of your birth chart guide you towards peace, prosperity, and purpose. The stars illuminate your path — it is your karma and free will that determine the journey. Trust the divine plan and walk forward with courage and wisdom.', 160);
    doc.text(bless, 105, 120, { align: 'center' });
    doc.setFontSize(9); doc.setTextColor(120, 120, 120);
    doc.text(`Report generated: ${new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`, 105, 210, { align: 'center' });
    doc.text('JyotishConnect — Premium Vedic Astrology Platform', 105, 220, { align: 'center' });

    doc.save(`Kundli_Report_${formData.name || 'Report'}.pdf`);
}
