import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getTrans } from './i18n';

// jsPDF only supports Latin fonts (Helvetica/Courier/Times).
// Devanagari/Hindi cannot be rendered — so PDF always uses English names.
const EN = getTrans('en');

const _SIGNS_EN = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const _PLANETS_EN: Record<string,string> = { Sun:"Sun", Moon:"Moon", Mars:"Mars", Mercury:"Mercury", Jupiter:"Jupiter", Venus:"Venus", Saturn:"Saturn", Rahu:"Rahu (North Node)", Ketu:"Ketu (South Node)", Asc:"Ascendant" };

function pl(name: string) { return _PLANETS_EN[name] || name; }
function sg(sign: string) { return EN.signs[sign as keyof typeof EN.signs] || sign; }
function nk(id: number) { return EN.nakshatras?.[id - 1] || '—'; }

function H(doc: jsPDF, title: string, pg: number, total: number) {
    doc.setFillColor(15,15,35); doc.rect(0,0,210,22,'F');
    doc.setFontSize(7); doc.setTextColor(249,115,22); doc.setFont('helvetica','bold');
    doc.text('JyotishConnect', 15, 14);
    doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180);
    doc.text(title, 105, 14, {align:'center'});
    doc.text(`Page ${pg} / ${total}`, 195, 14, {align:'right'});
}

function ST(doc: jsPDF, text: string, y: number, r=249, g=115, b=22) {
    doc.setFontSize(13); doc.setTextColor(r,g,b); doc.setFont('helvetica','bold');
    doc.text(text, 15, y);
    doc.setDrawColor(r,g,b); doc.setLineWidth(0.4); doc.line(15,y+2,195,y+2);
    doc.setFont('helvetica','normal'); doc.setTextColor(30,30,30);
}

const LOCALE_NAMES: Record<string,string> = {
    en:'English', hi:'Hindi', mr:'Marathi', bn:'Bengali',
    gu:'Gujarati', ta:'Tamil', te:'Telugu', kn:'Kannada'
};

export async function generateKundliPDF(
    chart: any,
    formData: {name:string; dob:string; tob:string; birthplace:string},
    locale: string,
    imgs: {d1?:string|null; d9?:string|null; moon?:string|null; d10?:string|null}
) {
    // Always use English for PDF text (jsPDF Helvetica cannot render Devanagari/Tamil/Telugu etc.)
    // Locale is used only for the language label on the cover page.
    const langLabel = LOCALE_NAMES[locale] || 'English';
    // Use English nakshatra name (not locale-translated which garbles in PDF)
    const nakshatraEn = chart.nakshatra_en || chart.nakshatra || '—';
    const doc = new jsPDF('p','mm','a4');
    const TP = 18;

    // PAGE 1: Cover
    doc.setFillColor(10,10,30); doc.rect(0,0,210,297,'F');
    doc.setFillColor(249,115,22); doc.rect(0,118,210,58,'F');
    doc.setFontSize(30); doc.setTextColor(249,115,22); doc.setFont('helvetica','bold');
    doc.text('JyotishConnect', 105, 75, {align:'center'});
    doc.setFontSize(12); doc.setTextColor(200,200,200); doc.setFont('helvetica','normal');
    doc.text('Premium Vedic Astrology Report', 105, 90, {align:'center'});
    doc.setFontSize(22); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold');
    doc.text(formData.name || 'Your Name', 105, 140, {align:'center'});
    doc.setFontSize(10); doc.setTextColor(255,220,180); doc.setFont('helvetica','normal');
    doc.text(`${formData.dob}  |  ${formData.tob}  |  ${formData.birthplace}`, 105, 153, {align:'center'});
    doc.setFontSize(10); doc.setTextColor(150,150,150);
    doc.text(`Lagna: ${sg(chart.ascendantSign)}  |  Rasi: ${sg(chart.moonSign)}  |  Nakshatra: ${nakshatraEn}`, 105, 200, {align:'center'});
    // Show language label so user knows this PDF matches their selected language
    doc.setFontSize(8); doc.setTextColor(120,100,60);
    doc.text(`Report Language: ${langLabel}  |  Numerical data identical across all languages`, 105, 265, {align:'center'});
    doc.setFontSize(7); doc.setTextColor(80,80,80); doc.text('Generated by JyotishConnect  —  jyotishconnect.com', 105, 280, {align:'center'});

    // PAGE 2: Birth Details + Avakahada
    doc.addPage(); H(doc,'Birth Attributes & Avakahada',2,TP);
    ST(doc,'Birth Details',32);
    autoTable(doc,{
        startY:37, margin:{left:15},
        head:[['Field','Value']],
        body:[
            ['Name', formData.name],
            ['Date of Birth', formData.dob],
            ['Time of Birth', formData.tob],
            ['Place of Birth', formData.birthplace],
            ['Lagna (Ascendant)', sg(chart.ascendantSign)],
            ['Moon Sign (Rasi)', sg(chart.moonSign)],
            ['Nakshatra (Birth Star)', nakshatraEn],
            ['Nakshatra Pada', chart.nakshatraPada ? `Pada ${chart.nakshatraPada}` : '—'],
            ['Nakshatra Number', chart.nakshatraId ? `#${chart.nakshatraId}` : '—'],
            ['Report Language', langLabel],
        ],
        styles:{fontSize:10,cellPadding:4},
        headStyles:{fillColor:[249,115,22],textColor:255},
        alternateRowStyles:{fillColor:[250,250,250]},
    });
    const y2=(doc as any).lastAutoTable.finalY+10;
    ST(doc,'Avakahada Chakra',y2,79,70,229);
    autoTable(doc,{
        startY:y2+5, margin:{left:15},
        head:[['Attribute','Value','Attribute','Value']],
        body:[
            ['Varna', chart.avakahada?.varna||'—', 'Vashya', chart.avakahada?.vashya||'—'],
            ['Tara',  chart.avakahada?.tara||'—',  'Yoni',   chart.avakahada?.yoni||'—'],
            ['Gana',  chart.avakahada?.gana||'—',  'Nadi',   chart.avakahada?.nadi||'—'],
            ['Moon Lord (Rashish)', chart.avakahada?.rashish||'—', 'Bhakoot', chart.avakahada?.bhakoot||'—'],
        ],
        styles:{fontSize:10,cellPadding:4},
        headStyles:{fillColor:[79,70,229],textColor:255},
        alternateRowStyles:{fillColor:[248,248,255]},
    });

    // PAGE 3: Panchang
    doc.addPage(); H(doc,'Daily Panchang at Birth',3,TP);
    ST(doc,'Panchang Details',32);
    // Tithi & Yoga may be index-based — resolve to name
    const safeStr = (v: any) => (typeof v === 'string' && /^[\x00-\x7F]*$/.test(v)) ? v : '';
    const resolveIdx = (arr: string[]|undefined, v: any) => typeof v === 'number' ? (arr?.[v] || `#${v}`) : safeStr(v);
    const tithiVal = resolveIdx(EN.panchang?.tithi, chart.panchang?.tithi) || '—';
    const yogaVal  = resolveIdx(EN.panchang?.yoga,  chart.panchang?.yoga)  || '—';
    const karanVal = resolveIdx(EN.panchang?.karan, chart.panchang?.karana)|| '—';
    const varaVal  = resolveIdx(EN.panchang?.vara,  chart.panchang?.vara)  || '—';
    autoTable(doc,{
        startY:37, margin:{left:15},
        head:[['Panchang Element','Value']],
        body:[
            ['Tithi (Lunar Day)', tithiVal],
            ['Nakshatra (Birth Star)', nakshatraEn],
            ['Yoga', yogaVal],
            ['Karana', karanVal],
            ['Vara (Weekday)', varaVal],
            ['Sunrise', safeStr(chart.panchang?.sunrise) || '—'],
            ['Sunset',  safeStr(chart.panchang?.sunset)  || '—'],
        ],
        styles:{fontSize:11,cellPadding:5},
        headStyles:{fillColor:[30,90,180],textColor:255},
        alternateRowStyles:{fillColor:[245,248,255]},
    });

    // PAGES 4-7: Charts
    const chartDefs=[
        {img:imgs.d1, label:'Lagna / Birth Chart (D1)', pg:4},
        {img:imgs.d9, label:'Navamsa Chart (D9)',       pg:5},
        {img:imgs.moon,label:'Chandra Lagna (Moon Chart)',pg:6},
        {img:imgs.d10,label:'Dasamsa Chart (D10)',      pg:7},
    ];
    chartDefs.forEach(({img,label,pg})=>{
        doc.addPage(); H(doc,label,pg,TP);
        ST(doc,label,32);
        if(img){
            doc.addImage(img,'PNG',35,42,140,140);
        } else {
            doc.setFontSize(10); doc.setTextColor(120,120,120);
            doc.text('Chart image: switch to the Charts tab on the website, then re-download.', 105,120,{align:'center'});
            doc.setFontSize(9); doc.setTextColor(160,160,160);
            doc.text('(SVG charts render only when visible in the browser)', 105,132,{align:'center'});
        }
    });

    // PAGE 8: Planetary Positions
    doc.addPage(); H(doc,'Planetary Positions',8,TP);
    ST(doc,'Planetary Positions',32);
    autoTable(doc,{
        startY:38, margin:{left:15},
        head:[['Planet','Sign','Degree','Nakshatra','House','Status']],
        body:(chart.planets||[]).map((p:any)=>[
            pl(p.name),
            sg(p.sign),
            p.longitude != null ? `${Math.floor(p.longitude%30)}\u00b0 ${Math.floor((p.longitude%1)*60)}'` : '—',
            nk(p.nakshatraId) || '—',
            p.house != null ? String(p.house) : '—',
            p.isExalted ? 'Exalted' : p.isDebilitated ? 'Debilitated' : 'Neutral',
        ]),
        styles:{fontSize:9,cellPadding:3},
        headStyles:{fillColor:[109,40,217],textColor:255},
        alternateRowStyles:{fillColor:[248,245,255]},
        didParseCell:(data:any)=>{
            if(data.column.index===5){
                if(data.cell.raw==='Exalted') data.cell.styles.textColor=[34,197,94];
                if(data.cell.raw==='Debilitated') data.cell.styles.textColor=[220,38,38];
            }
        },
    });

    // PAGE 9: Dasha Timeline
    doc.addPage(); H(doc,'Vimshottari Dasha',9,TP);
    ST(doc,'Current Active Dasha',32);
    // currentLords may be strings or array — normalise
    const rawLords = chart.dasha?.currentLords || [];
    const lords = Array.isArray(rawLords) ? rawLords : [];
    // Also try deriving from periods array if currentLords empty
    const now = Date.now();
    const activePeriod = (chart.dasha?.periods||[]).find((p:any) => {
        const s = new Date(p.start).getTime(), e = new Date(p.end).getTime();
        return now >= s && now <= e;
    });
    const maha = lords[0] || activePeriod?.lord || '—';
    const antar = lords[1] || '—';
    const pratyantar = lords[2] || '—';
    autoTable(doc,{
        startY:38, margin:{left:15}, tableWidth:120,
        head:[['Dasha Level','Planet Lord']],
        body:[
            ['Mahadasha (Major Period)',  pl(maha)],
            ['Antardasha (Sub Period)',   pl(antar)],
            ['Pratyantardasha (Minor)',   pl(pratyantar)],
        ],
        styles:{fontSize:11,cellPadding:5},
        headStyles:{fillColor:[249,115,22],textColor:255},
    });
    const y9=(doc as any).lastAutoTable.finalY+10;
    ST(doc,'Full Mahadasha Timeline (Vimshottari — 120 Year Cycle)',y9,79,70,229);
    const periods = chart.dasha?.periods || [];
    if(periods.length===0){
        doc.setFontSize(10); doc.setTextColor(120,120,120);
        doc.text('Dasha period data not available. Please regenerate the Kundli.', 15, y9+12);
    } else {
        autoTable(doc,{
            startY:y9+5, margin:{left:15},
            head:[['Planet','Start','End','Duration','Status']],
            body:periods.map((p:any)=>{
                const now=Date.now();
                const s=new Date(p.start), e=new Date(p.end);
                const active=now>=s.getTime()&&now<=e.getTime();
                const past=now>e.getTime();
                return[
                    pl(p.lord),
                    s.toLocaleDateString('en-IN',{year:'numeric',month:'short'}),
                    e.toLocaleDateString('en-IN',{year:'numeric',month:'short'}),
                    `${Math.round(p.duration)} yrs`,
                    active?'>> ACTIVE NOW':past?'Completed':'Upcoming',
                ];
            }),
            styles:{fontSize:9,cellPadding:3},
            headStyles:{fillColor:[79,70,229],textColor:255},
            alternateRowStyles:{fillColor:[248,248,255]},
            didParseCell:(data:any)=>{
                if(data.column.index===4&&String(data.cell.raw).includes('ACTIVE')){
                    data.cell.styles.textColor=[249,115,22];
                    data.cell.styles.fontStyle='bold';
                }
            },
        });
    }

    // PAGE 10: Ashtakvarga
    doc.addPage(); H(doc,'Ashtakvarga Analysis',10,TP);
    ST(doc,'Sarvashtakvarga — Strength Score per Zodiac Sign',32);
    doc.setFontSize(8.5); doc.setTextColor(100,100,100);
    doc.text('Score Guide: 30+ = Excellent  |  25-29 = Good  |  20-24 = Medium  |  Below 20 = Weak', 15,41);
    const total672=_SIGNS_EN.reduce((acc:number,_:string,i:number)=>acc+(chart.ashtakvarga?.sarva?.[i]||28),0);
    doc.setFontSize(9); doc.setTextColor(79,70,229);
    doc.text(`Total Sarvashtakvarga Score: ${total672} / 337 (avg ${(total672/12).toFixed(1)} per sign)`, 15, 47);
    autoTable(doc,{
        startY:52, margin:{left:15},
        head:[['Sign','Pts','Strength','Sign','Pts','Strength']],
        body:(()=>{
            const rows:any[]=[];
            const sarva = chart.ashtakvarga?.sarva || [];
            for(let i=0;i<12;i+=2){
                const p1 = typeof sarva[i]   === 'number' ? sarva[i]   : 28;
                const p2 = typeof sarva[i+1] === 'number' ? sarva[i+1] : 28;
                const s=(n:number)=>n>=30?'Excellent':n>=25?'Good':n>=20?'Medium':'Weak';
                rows.push([_SIGNS_EN[i], p1, s(p1), _SIGNS_EN[i+1], p2, s(p2)]);
            }
            return rows;
        })(),
        styles:{fontSize:10,cellPadding:4},
        headStyles:{fillColor:[161,98,7],textColor:255},
        alternateRowStyles:{fillColor:[255,251,235]},
        didParseCell:(data:any)=>{
            const v=data.cell.raw;
            if(v==='Excellent') data.cell.styles.textColor=[22,163,74];
            if(v==='Good')      data.cell.styles.textColor=[59,130,246];
            if(v==='Medium')    data.cell.styles.textColor=[161,98,7];
            if(v==='Weak')      data.cell.styles.textColor=[220,38,38];
        },
    });

    // PAGE 11: Doshas
    doc.addPage(); H(doc,'Dosha Analysis',11,TP);
    ST(doc,'Dosha Analysis',32);
    let yD=40;
    Object.entries(chart.doshas||{}).forEach(([key,data]:any)=>{
        const info=EN.doshas?.[key as keyof typeof EN.doshas] as any;
        const name=info?.name||key;
        const desc=info?.description||data.description||'No major influence detected in this area.';
        const rems:string[]=data.present?(info?.remedies||[]):[];
        const boxH=32+rems.length*5.5;
        if(yD+boxH>268){doc.addPage();H(doc,'Dosha Analysis (contd.)',11,TP);yD=30;}
        const bg=data.present?[255,240,240]:[240,255,245];
        const bc=data.present?[220,50,50]:[34,197,94];
        doc.setFillColor(bg[0],bg[1],bg[2]);
        doc.setDrawColor(bc[0],bc[1],bc[2]);
        doc.setLineWidth(0.5);
        doc.roundedRect(15,yD,180,boxH,2,2,'FD');
        doc.setFontSize(11); doc.setTextColor(30,30,30); doc.setFont('helvetica','bold');
        doc.text(`${name}  —  ${data.present?'PRESENT':'ABSENT'}`, 20, yD+8);
        doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(70,70,70);
        const dL=doc.splitTextToSize(desc,168);
        doc.text(dL,20,yD+15);
        if(rems.length){
            const ry=yD+15+dL.length*5;
            doc.setFontSize(8); doc.setTextColor(249,115,22);
            doc.text('Remedies:',20,ry);
            doc.setTextColor(60,60,60);
            rems.forEach((r:string,ri:number)=>doc.text(`- ${r}`,24,ry+5+ri*5.5));
        }
        yD+=boxH+6;
    });

    // PAGES 12-16: Life Predictions — always use English predictions for PDF
    const predData = chart.predictionsEn || chart.predictions || {};
    Object.entries(predData).forEach(([area,text]:any,pi)=>{
        doc.addPage();
        const label=(EN.labels?.life_predictions as any)?.[area]||area;
        H(doc,label,12+pi,TP);
        ST(doc,label,32,79,70,229);
        // Add language note for non-English users
        if(locale !== 'en') {
            doc.setFontSize(8); doc.setTextColor(120,100,60);
            doc.text(`Note: Predictions shown in English. Native ${langLabel} version available on website.`, 15, 40);
        }
        doc.setFontSize(11); doc.setTextColor(40,40,40);
        const safeText = typeof text === 'string' && /^[\x00-\xFF]*$/.test(text)
            ? text : 'Prediction data not available. Please view on website for native language.';
        const lines=doc.splitTextToSize(safeText, 175);
        doc.text(lines, 15, locale !== 'en' ? 46 : 44);
    });

    // PAGE 17: Remedies & Gemstones
    doc.addPage(); H(doc,'Remedies & Gemstones',17,TP);
    ST(doc,'Gemstone Recommendations',32);
    autoTable(doc,{
        startY:38, margin:{left:15},
        head:[['Type','Gemstone','Wear Day','Finger','Metal','Weight','Mantra']],
        body:[
            ['Life Stone',    EN.gemstones.Sun||'Ruby',             'Sunday',   'Ring Finger',   'Gold',  '3-5 Ratti','Om Suryaya Namah'],
            ['Lucky Stone',   EN.gemstones.Jupiter||'Yel. Sapphire','Thursday', 'Index Finger',  'Gold',  '5-7 Ratti','Om Guruve Namah'],
            ['Benefic Stone', EN.gemstones.Moon||'Pearl',           'Monday',   'Little Finger', 'Silver','5-7 Ratti','Om Chandraya Namah'],
        ],
        styles:{fontSize:8.5,cellPadding:3},
        headStyles:{fillColor:[161,98,7],textColor:255},
        alternateRowStyles:{fillColor:[255,251,235]},
    });
    const yR=(doc as any).lastAutoTable.finalY+10;
    ST(doc,'Spiritual Remedies',yR,79,70,229);
    autoTable(doc,{
        startY:yR+5, margin:{left:15},
        head:[['Remedy','Detailed Instructions']],
        body:[
            ['Mahadasha Remedy', `${pl(chart.dasha?.currentLords?.[0]||'Sun')} Mahadasha is active. Recite its Beej Mantra 108 times daily, preferably after sunrise.`],
            ['Shani (Saturn) Remedy', 'Every Saturday, offer water to a peepal tree. Donate black sesame, urad dal, or mustard oil. Install Shani Yantra at home.'],
            ['Mangal (Mars) Remedy', 'Every Tuesday, recite Hanuman Chalisa. Donate red cloth or red lentils. Blood donation is also highly beneficial.'],
            ['Surya (Sun) Remedy', 'Every morning, offer water to the Sun with red flowers and sandalwood. Recite Aditya Hridayam. Wear copper ring on right hand.'],
            ['Rahu Remedy', 'Donate blue/black items on Saturdays. Recite "Om Rahave Namah" 18 times. Avoid non-vegetarian food on Saturdays.'],
        ],
        styles:{fontSize:9.5,cellPadding:4},
        headStyles:{fillColor:[79,70,229],textColor:255},
        alternateRowStyles:{fillColor:[245,245,255]},
        columnStyles:{0:{fontStyle:'bold',cellWidth:42}},
    });

    // PAGE 18: Conclusion
    doc.addPage(); H(doc,'Summary & Blessings',18,TP);
    doc.setFillColor(10,10,30); doc.rect(0,22,210,275,'F');
    doc.setFontSize(20); doc.setTextColor(249,115,22); doc.setFont('helvetica','bold');
    doc.text('Blessings & Divine Guidance', 105, 80, {align:'center'});
    doc.setFontSize(12); doc.setTextColor(200,200,200); doc.setFont('helvetica','normal');
    doc.text(`Dear ${formData.name},`, 105, 105, {align:'center'});
    const bl=doc.splitTextToSize('May the celestial alignments of your birth chart guide you towards peace, prosperity, and purpose. The stars illuminate your path — it is your karma and free will that shape your destiny. Walk forward with courage and wisdom, guided by the divine light of Jyotish.', 160);
    doc.text(bl, 105, 118, {align:'center'});
    doc.setFontSize(10); doc.setTextColor(150,150,150);
    doc.text(`Lagna: ${sg(chart.ascendantSign)}  |  Moon Sign: ${sg(chart.moonSign)}  |  Nakshatra: ${nakshatraEn}`, 105, 185, {align:'center'});
    doc.text(`Active Mahadasha: ${pl(maha)}  |  Antardasha: ${pl(antar)}`, 105, 195, {align:'center'});
    doc.setFontSize(8); doc.setTextColor(100,100,100);
    doc.text(`Report generated: ${new Date().toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}`, 105, 215, {align:'center'});
    doc.text('JyotishConnect — Premium Vedic Astrology Platform', 105, 225, {align:'center'});

    doc.save(`Kundli_Report_${formData.name||'Report'}.pdf`);
}
