export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen py-12">
            <div className="container mx-auto px-4 max-w-4xl">
                {/* Header */}
                <div className="text-center mb-12">
                    <h1 className="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-primary via-purple-500 to-pink-500 bg-clip-text text-transparent">
                        Terms of Service
                    </h1>
                    <p className="text-muted-foreground">
                        Last Updated: March 24, 2026
                    </p>
                </div>

                {/* Content */}
                <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">

                    {/* Introduction */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">Introduction</h2>
                        <p className="text-muted-foreground leading-relaxed">
                            Welcome to JyotishConnect ("<strong>Platform</strong>", "<strong>we</strong>", "<strong>us</strong>",
                            or "<strong>our</strong>"). These Terms of Service ("<strong>Terms</strong>") govern your access to and
                            use of our astrology consultation platform, AI tools, and related services.
                        </p>
                        <p className="text-muted-foreground leading-relaxed mt-4">
                            By accessing or using our Platform, you explicitly agree to be bound by these Terms and our Privacy Policy.
                            If you do not agree with these Terms, please immediately cease using our services.
                        </p>
                    </section>

                    {/* Important Disclaimer */}
                    <section className="p-6 rounded-lg border border-amber-500/30 bg-amber-500/5">
                        <h2 className="text-2xl font-bold mb-4 text-amber-600">⚠️ Critical Legal Disclaimer</h2>
                        <p className="text-muted-foreground leading-relaxed mb-4">
                            <strong>Astrology is a traditional belief system and an interpretive art. It is not a science.</strong> Services provided
                            on this Platform, including human astrologer consultations and AI-generated text ("Sarvagya"), are strictly for entertainment, spiritual guidance, and recreational purposes only.
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li><strong>NO MEDICAL ADVICE:</strong> Astrological charts and predictions do not diagnose, treat, or cure ANY physical or mental illness. Do not alter medications or delay seeking medical professionals based on our charts.</li>
                            <li><strong>NO FINANCIAL/LEGAL ADVICE:</strong> We do not offer registered investment or legal advice. Do not make stock market, property, or legal decisions based solely on astrological alignments.</li>
                            <li><strong>NO GUARANTEES:</strong> We expressly disclaim any warranties or guarantees regarding the accuracy, reliability, or effectiveness of any prediction, mantra, or gemstone remedy.</li>
                        </ul>
                        <p className="text-muted-foreground mt-4">
                            <strong>You are solely responsible for any decisions or actions you take based on the Platform.</strong> By using this Platform, you agree to hold JyotishConnect and its astrologers entirely harmless from any resulting damages.
                        </p>
                    </section>

                    {/* AI Services */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">1. AI Assistant ("Sarvagya") Limitations</h2>
                        <p className="text-muted-foreground mb-4">
                            JyotishConnect employs advanced machine learning algorithms ("Sarvagya") to assist with Kundli interpretation and daily horoscopes. You understand and agree that:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>AI outputs are inherently prone to "hallucinations" or logical errors and should be treated as automated novelty text.</li>
                            <li>The AI does not possess human intuition, nor is it a licensed professional.</li>
                            <li>We accept zero liability for any offensive, inaccurate, or distressing statements generated by the AI interface.</li>
                        </ul>
                    </section>

                    {/* Platform Role */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">2. Platform as an Intermediary</h2>
                        <p className="text-muted-foreground mb-4">
                            JyotishConnect acts solely as an <strong>intermediary technology platform</strong> facilitating communication
                            between users and independent astrologers via video, audio, and chat.
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>Astrologers are independent contractors, NOT employees of JyotishConnect.</li>
                            <li>We do not control the specific interpretive advice given during your private video/chat sessions.</li>
                            <li>We do not insure or bond the astrologers on our platform.</li>
                        </ul>
                    </section>

                    {/* Payments */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">3. Payments, Wallet, and Third-Party Gateways</h2>
                        <h3 className="text-xl font-semibold mb-3">3.1 Payment Processing</h3>
                        <p className="text-muted-foreground mb-4">
                            All payments are securely processed via certified third-party vendors (e.g., Razorpay). JyotishConnect does not directly collect, store, or transmit your credit card or banking PINs. We are not liable for technical outages on the Razorpay gateway.
                        </p>

                        <h3 className="text-xl font-semibold mb-3 mt-6">3.2 The Astro Wallet</h3>
                        <p className="text-muted-foreground">
                            Funds deposited into your "Astro Wallet" are purely digital credits meant for purchasing consultation minutes on the Platform. Wallet balances are non-transferable, do not accrue interest, and cannot be withdrawn as fiat currency to a bank account.
                        </p>
                    </section>

                    {/* Refund Policy */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">4. Refund and Cancellation Policy</h2>
                        <p className="text-muted-foreground mb-4">
                            To protect our astrologers' time, our refund window is extremely strict:
                        </p>

                        <h3 className="text-xl font-semibold mb-3">4.1 Eligible for Full Refund:</h3>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>Server crash or catastrophic failure of our video/chat infrastructure preventing the meeting.</li>
                            <li>The Astrologer fails to join the Google Meet / Consultation Room within 10 minutes of the scheduled time.</li>
                        </ul>

                        <h3 className="text-xl font-semibold mb-3 mt-6">4.2 NOT Eligible for Refund:</h3>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>Dissatisfaction with the Astrologer's predictions, tone, or advice.</li>
                            <li>The prediction does not come true.</li>
                            <li>User failing to join the meeting room on time (No-show).</li>
                            <li>User internet connectivity failures dropping the video call.</li>
                        </ul>
                    </section>

                    {/* User Conduct */}
                    <section className="p-6 rounded-lg border border-red-500/30 bg-red-500/5">
                        <h2 className="text-2xl font-bold mb-4 text-red-600">5. Prohibited Conduct</h2>
                        <p className="text-muted-foreground mb-4">
                            Engaging in the following will result in an immediate, permanent ban with no refund of wallet balance:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>Using profanity, sexual remarks, threats, or harassment against any Astrologer during chat or video sessions.</li>
                            <li>Soliciting Astrologers for offline consultations or sharing direct phone numbers/WhatsApp to bypass platform fees.</li>
                            <li>Creating multiple accounts to exploit promotional discounts.</li>
                            <li>Recording video/audio consultations without the explicit, recorded consent of the Astrologer.</li>
                        </ul>
                    </section>

                    {/* Limitation of Liability */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">6. Limitation of Liability</h2>
                        <p className="text-muted-foreground mb-4">
                            To the maximum extent permitted by applicable Indian law:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                            <li>JyotishConnect and its parent company, directors, and employees shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages.</li>
                            <li>This includes, but is not limited to, loss of profits, data, marriage failure, or business interruption arising from the use or inability to use our services.</li>
                            <li>Our total cumulative liability to you for any claim arising out of these Terms shall be strictly limited to the amount you paid to us for the specific consultation/service in dispute over the past 30 days.</li>
                        </ul>
                    </section>
                    
                    {/* Governing Law */}
                    <section className="p-6 rounded-lg border border-primary/20 bg-card/50 backdrop-blur-sm">
                        <h2 className="text-2xl font-bold mb-4">7. Governing Law and Dispute Resolution</h2>
                        <p className="text-muted-foreground">
                            These Terms are governed by the laws of India. Any legal dispute, claim, or controversy arising out of or relating to your use of JyotishConnect shall be subject to the exclusive jurisdiction of the competent civil courts located in <strong>New Delhi, India</strong>.
                        </p>
                    </section>

                </div>
            </div>
        </div>
    );
}
